### PR TITLE
Add support for ClassVar variables

### LINKED ISSUE #226: Suggestion: exclude ClassVar from schema
Hi there,

I'm using strictly typed pandas and one thing I've encountered is that it's not possible to declare class variables, for example the below raises an error:
```python
from strictly_typed_pandas import DataSet
from typing import ClassVar

class A:
    a: int
    b: ClassVar[str] = 'abc'

ds = DataSet[A]({'a': [1,2,3]})
```

Would it be possible to exclude classvars from the schema? Looking at the code it seems pretty doable, either by adding to [the dataset init](https://github.com/nanne-aben/strictly_typed_pandas/blob/2a13fce3e42b0dad93ce2e72d067b32f71b9ba07/strictly_typed_pandas/dataset.py#L109) or [schema validation](https://github.com/nanne-aben/strictly_typed_pandas/blob/2a13fce3e42b0dad93ce2e72d067b32f71b9ba07/strictly_typed_pandas/validate_schema.py#L17).

something like the below:
```python
from typing import ClassVar, get_origin
import inspect

class A:
    a: int
    b: ClassVar[str] = 'abc'

ann = inspect.get_annotations(A, eval_str=True)

ann = {
    var_name: var_type
    for var_name, var_type in ann.items() if get_origin(var_type) is not ClassVar
}
```
This would mean if someone tries to define a `ClassVar` and member variable the result would depend on the order of declaration but... Don't.

I'll try to make a PR this evening. Otherwise very useful module.

### PR DESCRIPTION
**Pull request by alwaysmpe**
fixes #226 
(different account - same user, this is my personal account)

### CODE REVIEW

**Comment by alwaysmpe** [comment]
tests needed, wip

**Comment by nanne-aben** [comment]
Nice work! Could you add some documentation to `docs/source/advanced.ipynb`? I think adding a section between `Support for numpy and pandas data types` and `IndexedDataSet` would make most sense.

**Comment by alwaysmpe** [comment]
Good idea, I've added as suggested

**Review by nanne-aben — APPROVED** [review]
LGTM, thank you for your contribution!

**Pull request merged**
